//
// Milkyway Hierarchical Verilog Dump:
// Generated on 10/28/2021 at 08:47:08
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :CHIP
// Cell Name    :vending_machine
// Hierarchy delimiter:'/'
// Write Command : write_verilog -unconnected_ports -diode_ports -wire_declaration -keep_backslash_before_hiersep  
//   CHIP_pr.v
//


module vending_machine (rst , clk , out15 , out10 , out5 , out_water , 
    in10 , in5 , cancel , buy );
input  rst ;
input  clk ;
output out15 ;
output out10 ;
output out5 ;
output out_water ;
input  in10 ;
input  in5 ;
input  cancel ;
input  buy ;

/* wire declarations */

wire N63 ;
wire n12 ;
wire SYNOPSYS_UNCONNECTED_0 ;
wire SYNOPSYS_UNCONNECTED_1 ;
wire SYNOPSYS_UNCONNECTED_2 ;
wire SYNOPSYS_UNCONNECTED_3 ;
wire SYNOPSYS_UNCONNECTED_4 ;
wire SYNOPSYS_UNCONNECTED_5 ;
wire SYNOPSYS_UNCONNECTED_6 ;
wire SYNOPSYS_UNCONNECTED_7 ;
wire SYNOPSYS_UNCONNECTED_8 ;
wire SYNOPSYS_UNCONNECTED_9 ;
wire SYNOPSYS_UNCONNECTED_10 ;
wire SYNOPSYS_UNCONNECTED_11 ;
wire SYNOPSYS_UNCONNECTED_12 ;
wire SYNOPSYS_UNCONNECTED_13 ;
wire SYNOPSYS_UNCONNECTED_14 ;
wire SYNOPSYS_UNCONNECTED_15 ;
wire N61 ;
wire [3:0] state ;
wire n51 ;
wire N64 ;
wire n54 ;
wire n52 ;
wire N62 ;
wire n53 ;
wire N91 ;
wire SYNOPSYS_UNCONNECTED_16 ;
wire N92 ;
wire SYNOPSYS_UNCONNECTED_17 ;
wire N93 ;
wire SYNOPSYS_UNCONNECTED_18 ;
wire N90 ;
wire SYNOPSYS_UNCONNECTED_19 ;
wire n29 ;
wire n41 ;
wire n36 ;
wire n30 ;
wire n34 ;
wire n44 ;
wire n33 ;
wire n50 ;
wire n37 ;
wire n31 ;
wire n32 ;
wire n49 ;
wire n38 ;
wire n39 ;
wire n35 ;
wire n42 ;
wire n43 ;
wire n40 ;
wire n46 ;
wire n48 ;
wire n45 ;
wire n47 ;

BUF_X1 U1 (.A ( N63 ) , .Z ( n12 ) ) ;
PADIOVSS io_vss7 (.VSSIO ( SYNOPSYS_UNCONNECTED_2 ) ) ;
PADIOVSS io_vss6 (.VSSIO ( SYNOPSYS_UNCONNECTED_3 ) ) ;
PADIOVSS io_vss5 (.VSSIO ( SYNOPSYS_UNCONNECTED_4 ) ) ;
PADIOVSS io_vss4 (.VSSIO ( SYNOPSYS_UNCONNECTED_5 ) ) ;
PADIOVSS io_vss3 (.VSSIO ( SYNOPSYS_UNCONNECTED_6 ) ) ;
PADIOVSS io_vss2 (.VSSIO ( SYNOPSYS_UNCONNECTED_7 ) ) ;
PADIOVSS io_vss1 (.VSSIO ( SYNOPSYS_UNCONNECTED_8 ) ) ;
PADIOVDD io_vdd6 (.VDDIO ( SYNOPSYS_UNCONNECTED_9 ) ) ;
PADIOVDD io_vdd5 (.VDDIO ( SYNOPSYS_UNCONNECTED_10 ) ) ;
PADIOVDD io_vdd4 (.VDDIO ( SYNOPSYS_UNCONNECTED_11 ) ) ;
PADIOVDD io_vdd3 (.VDDIO ( SYNOPSYS_UNCONNECTED_12 ) ) ;
PADIOVDD io_vdd2 (.VDDIO ( SYNOPSYS_UNCONNECTED_13 ) ) ;
PADIOVDD io_vdd1 (.VDDIO ( SYNOPSYS_UNCONNECTED_14 ) ) ;
PADIOVDDPOC io_vdd7 (.VDDIO ( SYNOPSYS_UNCONNECTED_15 ) ) ;
DFF_X1 \state_reg[0] (.D ( N61 ) , .CK ( clk ) , .Q ( state[0] ) , .QN ( n51 ) ) ;
DFF_X1 \state_reg[3] (.D ( N64 ) , .CK ( clk ) , .Q ( state[3] ) , .QN ( n54 ) ) ;
DFF_X1 \state_reg[2] (.D ( n12 ) , .CK ( clk ) , .Q ( state[2] ) , .QN ( n52 ) ) ;
DFF_X1 \state_reg[1] (.D ( N62 ) , .CK ( clk ) , .Q ( state[1] ) , .QN ( n53 ) ) ;
DFF_X1 out5_reg (.D ( N91 ) , .CK ( clk ) , .Q ( out5 ) 
    , .QN ( SYNOPSYS_UNCONNECTED_16 ) ) ;
DFF_X1 out10_reg (.D ( N92 ) , .CK ( clk ) , .Q ( out10 ) 
    , .QN ( SYNOPSYS_UNCONNECTED_17 ) ) ;
DFF_X1 out15_reg (.D ( N93 ) , .CK ( clk ) , .Q ( out15 ) 
    , .QN ( SYNOPSYS_UNCONNECTED_18 ) ) ;
DFF_X1 out_water_reg (.D ( N90 ) , .CK ( clk ) , .Q ( out_water ) 
    , .QN ( SYNOPSYS_UNCONNECTED_19 ) ) ;
NAND2_X1 U39 (.A1 ( state[2] ) , .A2 ( n54 ) , .ZN ( n29 ) ) ;
AOI221_X1 U40 (.A ( n29 ) , .B1 ( state[0] ) , .B2 ( state[1] ) , .C1 ( n51 ) 
    , .C2 ( n53 ) , .ZN ( N90 ) ) ;
NOR3_X1 U41 (.A1 ( state[3] ) , .A2 ( n52 ) , .A3 ( n53 ) , .ZN ( N91 ) ) ;
NAND2_X1 U42 (.A1 ( n52 ) , .A2 ( n53 ) , .ZN ( n41 ) ) ;
NOR3_X1 U43 (.A1 ( n54 ) , .A2 ( n51 ) , .A3 ( n41 ) , .ZN ( N93 ) ) ;
NOR3_X1 U44 (.A1 ( state[0] ) , .A2 ( n54 ) , .A3 ( n41 ) , .ZN ( N92 ) ) ;
NOR2_X1 U45 (.A1 ( cancel ) , .A2 ( in5 ) , .ZN ( n36 ) ) ;
NOR2_X1 U46 (.A1 ( state[1] ) , .A2 ( state[0] ) , .ZN ( n30 ) ) ;
AOI22_X1 U47 (.A1 ( state[0] ) , .A2 ( n36 ) , .B1 ( n30 ) , .B2 ( buy ) 
    , .ZN ( n34 ) ) ;
NOR2_X1 U48 (.A1 ( rst ) , .A2 ( state[3] ) , .ZN ( n44 ) ) ;
NAND2_X1 U49 (.A1 ( n44 ) , .A2 ( n52 ) , .ZN ( n33 ) ) ;
NAND4_X1 U50 (.A1 ( n53 ) , .A2 ( n51 ) , .A3 ( n44 ) , .A4 ( state[2] ) 
    , .ZN ( n50 ) ) ;
INV_X1 U51 (.A ( n50 ) , .ZN ( n37 ) ) ;
INV_X1 U52 (.A ( n36 ) , .ZN ( n31 ) ) ;
NAND2_X1 U53 (.A1 ( n37 ) , .A2 ( n31 ) , .ZN ( n32 ) ) ;
NAND3_X1 U54 (.A1 ( n52 ) , .A2 ( n44 ) , .A3 ( state[1] ) , .ZN ( n49 ) ) ;
INV_X1 U55 (.A ( n49 ) , .ZN ( n38 ) ) ;
NAND3_X1 U56 (.A1 ( n38 ) , .A2 ( n51 ) , .A3 ( n31 ) , .ZN ( n39 ) ) ;
OAI211_X1 U57 (.A ( n32 ) , .B ( n39 ) , .C1 ( n34 ) , .C2 ( n33 ) , .ZN ( N61 ) ) ;
NOR2_X1 U58 (.A1 ( cancel ) , .A2 ( n51 ) , .ZN ( n35 ) ) ;
OAI211_X1 U59 (.A ( n44 ) , .B ( n35 ) , .C1 ( in10 ) , .C2 ( in5 ) , .ZN ( n42 ) ) ;
INV_X1 U60 (.A ( in10 ) , .ZN ( n43 ) ) ;
OAI221_X1 U61 (.A ( n36 ) , .B1 ( in10 ) , .B2 ( n38 ) , .C1 ( n43 ) 
    , .C2 ( n37 ) , .ZN ( n40 ) ) ;
OAI211_X1 U62 (.A ( n40 ) , .B ( n39 ) , .C1 ( n42 ) , .C2 ( n41 ) , .ZN ( N62 ) ) ;
INV_X1 U63 (.A ( n42 ) , .ZN ( n46 ) ) ;
INV_X1 U64 (.A ( cancel ) , .ZN ( n48 ) ) ;
AOI221_X1 U65 (.A ( state[0] ) , .B1 ( in5 ) , .B2 ( n48 ) , .C1 ( n43 ) 
    , .C2 ( n48 ) , .ZN ( n45 ) ) ;
OAI211_X1 U66 (.A ( n44 ) , .B ( state[1] ) , .C1 ( n46 ) , .C2 ( n45 ) 
    , .ZN ( n47 ) ) ;
OAI22_X1 U67 (.A1 ( state[2] ) , .A2 ( n47 ) , .B1 ( cancel ) , .B2 ( n50 ) 
    , .ZN ( N63 ) ) ;
AOI221_X1 U68 (.A ( n48 ) , .B1 ( n51 ) , .B2 ( n50 ) , .C1 ( n49 ) , .C2 ( n50 ) 
    , .ZN ( N64 ) ) ;
PADCORNER cornerLL () ;
PADCORNER cornerLR () ;
PADCORNER cornerUL () ;
PADCORNER cornerUR () ;
PADVDD core_vdd1 () ;
PADVDD core_vdd2 () ;
PADVDD core_vdd3 () ;
PADVDD core_vdd4 () ;
PADVSS core_vss1 () ;
PADVSS core_vss2 () ;
PADVSS core_vss3 () ;
PADVSS core_vss4 () ;
endmodule


